=== samanthatuhseng/TrendGPT/GPT/privateGPT/tweets_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
      "text": {
        "type": "string"
      },
      "permanent_url": {
        "type": "string"
      },
      "author": {
        "type": "string"
      },
      "Retweets": {
        "type": "integer"
      },
      "likes": {
        "type": "integer"
      }
    }
  }

=== samanthatuhseng/TrendGPT/GPT/scraper/tweets.json
[{"text":"OMG. “The best collateral “ in the world, the 1 month T-Bill went up by 100 basis points. Does this mesn the world banking system is collapsing?\nSo much for all those experts who recommended 1 month T-Bills. Stick with Gold, Silver, Bitcoin, and home defense now….not tomorrow.","permanent_url":"https://twitter.com/theRealKiyosaki/status/1655303145436897280","author":"Robert Kiyosaki","Retweets":508,"likes":3280},{"text":"It's #Bitcoin Conference week! Who will be in Miami?! :)\n\nYou can still get tickets at https://t.co/eNohzmkPUW -- use code HODL for a discount.\n\nWho better to feature on the show this week than the one and only @jackmallers. Episode drops tomorrow. \nhttps://t.co/Yp1RprvwEf https://t.co/E1oHTWQgLh","permanent_url":"https://twitter.com/natbrunell/status/1658087861697085440","author":"Natalie Brunell ⚡️","Retweets":197,"likes":1268},{"text":"#Ethereum what if the solution to expensive transactions was just around the corner?","permanent_url":"https://twitter.com/RichardHeartWin/status/1656810877989924867","author":"Richard Heart","Retweets":1280,"likes":5447},{"text":"Good morning!!! Keep going $PEPE 🚀🚀🚀🚀🚀🚀 what else are we looking at in #Crypto this weekend? https://t.co/Aco7gWAb6v","permanent_url":"https://twitter.com/Yourpop8/status/1657331381876187139","author":"YourPOP","Retweets":287,"likes":1297},{"text":"Where are my $POOH bears?\n\nLolololol","permanent_url":"https://twitter.com/Bitboy_Crypto/status/1654847005905043456","author":"Ben Armstrong","Retweets":189,"likes":883},{"text":"United so poor in this game. ETH seeing more of the players in these situations is a positive. Allows him to sort out who he wants on the bus. The real disgrace are the Glazers. Are they waiting for the last game at OT to pass??? It would be typical of them. Weak and shirking…","permanent_url":"https://twitter.com/GNev2/status/1655301135371042816","author":"Gary Neville","Retweets":4345,"likes":37017},{"text":"$PEPE is cool, but have you heard about #Bitcoin?","permanent_url":"https://twitter.com/TheMoonCarl/status/1655317891523178496","author":"Carl From The Moon","Retweets":71,"likes":892},{"text":"I will be the meme you guys need today. But I was using metamask and uniswap before you existed in crypto.\n\nYou guys see the several approved transactions for 0 ETH? \n\nI approved the contract 4 times and it just updated the time. It kept showing it as one transaction. https://t.co/a4TvXRrRq0","permanent_url":"https://twitter.com/Bitboy_Crypto/status/1655273967962161153","author":"Ben Armstrong","Retweets":37,"likes":453},{"text":"You’re gifted $10,000 USDT to buy the current crypto market, what would you buy? \n\n$BTC \n$ETH \n$PEPE\n$CGPT\n$KEK\n$KASTA\n$BNB \n$VET\n$XRP\n$SFM\n$AVAX\n$ADA\n$MATIC\n$LTC\n$DOGE\n$TEL\n$MEE\n$XLM\n$EGLD \n$HERO\n$SAND\n$MANA\n$EOS\n$XVG\n$DOT\n$CRO\n$FEG \n$BEN\n$SHIB \n$FLOKI\n$KISHU \n\n👇🏻👇🏻👇🏻","permanent_url":"https://twitter.com/TheMoonCarl/status/1656297584363806720","author":"Carl From The Moon","Retweets":286,"likes":1324},{"text":"Digital ID linked to biometrics on a blockchain? Count me out. https://t.co/yQaldyuqaC","permanent_url":"https://twitter.com/coinbureau/status/1658049617357946882","author":"Coin Bureau","Retweets":87,"likes":468},{"text":"🔥 New IDO Project: Flappy Moonbird (FMB)\n\n✅ How to participate? Create your Bybit Wallet + 200USDC deposit on Ethereum chain    \n\n📆 Subscription: May 16, 2023, 10AM UTC to May 19, 2023, 10AM UTC\n\n📷 Snapshot: May 19, 10AM UTC  - May 22, 10AM UTC\n\n👉 https://t.co/K9yrQfNrQg https://t.co/ZVUzKSTPsW","permanent_url":"https://twitter.com/Bybit_Web3/status/1658421249654272001","author":"Bybit Web3","Retweets":3561,"likes":3340},{"text":"What Bitcoin NFT projects would you like to see on Binance NFT?\n\nTag your top 3 ⬇️","permanent_url":"https://twitter.com/TheBinanceNFT/status/1655882846987251713","author":"Binance NFT","Retweets":324,"likes":1212},{"text":"#Bitcoin in May? (Honestly)\n\n📉             ↔️               📈\n👇             👇               👇","permanent_url":"https://twitter.com/MMCrypto/status/1655147597626224640","author":"MMCrypto","Retweets":85,"likes":1235},{"text":"GM 🫡\n\n$BTC NFTs are ____?","permanent_url":"https://twitter.com/TheBinanceNFT/status/1656194084745125889","author":"Binance NFT","Retweets":62,"likes":379},{"text":"Crypto Startup School (CSS23) Spotlight 🔦\n\nTeam: @HelloBlockus\n\nFounders:\n@0Linglong0, @noweiitsmichael and @jessziyuezhang\n\nWhere is the team from?\nLinglong lives in San Francisco, and is from China. 🇨🇳 Michael lived in SF \u0026amp; Miami, and is from Houston, Texas. 🇺🇲 Jess lived in… https://t.co/sCr0A3xaOZ","permanent_url":"https://twitter.com/a16zcrypto/status/1656365150222561282","author":"a16z crypto","Retweets":19,"likes":114},{"text":"Banks gambled away your money lending it out for nearly 0% return. But instead of yielding nearly 0% they actually lost massively as the treasuries the government sold them plummeted in value. They're bankrupt. Why shouldn't their stocks go to $0? Real #Cryptocurrency solves this","permanent_url":"https://twitter.com/RichardHeartWin/status/1654184173727371275","author":"Richard Heart","Retweets":666,"likes":3030},{"text":"BTC is unusable. Why not use something else like BSV? https://t.co/r0I3c0L5Qg","permanent_url":"https://twitter.com/kurtwuckertjr/status/1655924968494972937","author":"Kurt ◉ GorillaPool.com","Retweets":47,"likes":278},{"text":".@CogitoProtocol is on a mission to change the game in the world of stablecoins with their cutting-edge “tracercoins.” 👀\n\nWhat are tracecoins?\n▪️ Decentralised assets, fully crypto-backed with risk-weighted reserves.\n▪️ Pegged to indices that track the progress of humanity.\n▪️… https://t.co/navMR9FgaW","permanent_url":"https://twitter.com/SeedifyFund/status/1655934770004762631","author":"Seedify","Retweets":12282,"likes":2850},{"text":"What will #Bitcoin see first?\n\n$20k                            $35k\n👇                                 👇","permanent_url":"https://twitter.com/MMCrypto/status/1656002504923181056","author":"MMCrypto","Retweets":137,"likes":3433},{"text":"Bears can call for a drop to $17k because of \"TA.\"\nI can call for $250k #Bitcoin before next halving.\nBears can call sub $10k because reasons.\nI can call $10,000,000 in the next 5 years because of a massive wave of corporate and nation-state adoption.\n\nSee the difference?","permanent_url":"https://twitter.com/Excellion/status/1658251118223462401","author":"Samson Mow","Retweets":118,"likes":1023},{"text":"Fees too high? \n\nHow do the Bitcoin puritans say it again? \n\nCry harder.","permanent_url":"https://twitter.com/danheld/status/1655256797974876160","author":"Dan Held 🧙‍♂️","Retweets":21,"likes":167},{"text":"I only have one question about $PEPE going from zero to top 100 coin in a month:\n\nWhy did it take crypto so long for someone to name a coin Pepe?\n\nIt's one of the largest memes on the internet.\n\nWe made food coins, Elon coins, dog breed coins, cumrocket coins...and finally Pepe. https://t.co/uChqQ8pyFN","permanent_url":"https://twitter.com/VentureCoinist/status/1652930048888827904","author":"Luke Martin","Retweets":14,"likes":567},{"text":"Why are crypto prices ending the week in the red? A few reasons 👇 https://t.co/I7qVIsNHC7","permanent_url":"https://twitter.com/coinbureau/status/1657037891644555265","author":"Coin Bureau","Retweets":104,"likes":763},{"text":"Are we hacked again? 🫣","permanent_url":"https://twitter.com/shadows_eth/status/1654226994618589184","author":"M. Shadows","Retweets":59,"likes":1734},{"text":"#Huobi Top Volume: \n\n🔹 $BTC     90.33M \n🔹 $ETH      25.31M\n🔹 $HT        13.58M\n🔹 $NEAR   11.20M\n🔹 $PEPE      7.05M\n\nWhich one do you HODL?\n\nTrade them at https://t.co/qihXWjx9DK https://t.co/SF2XdJcsgd","permanent_url":"https://twitter.com/HuobiGlobal/status/1658336774878560256","author":"Huobi","Retweets":95,"likes":340},{"text":"You guys wanna see a magic trick? 🤓 #bts of Mi helping me practice the crypto wallet swipe in the finale. Beyond grateful he took me under his wing in so many ways. Catch the whole first season on @hulu #wrappedbaby #thecompanyyoukeep ✨✨ https://t.co/uweQzfcnDO","permanent_url":"https://twitter.com/catherinehkim/status/1655750984294100993","author":"Catherine Haena Kim","Retweets":48,"likes":390},{"text":"Did you know that the #BITCOIN $PEPE on BRC-20 existed before the one you know existed?","permanent_url":"https://twitter.com/MMCrypto/status/1655484266955042816","author":"MMCrypto","Retweets":84,"likes":541},{"text":"When will #BTC have the next ATH?\n\nMake a guess 👇🏼","permanent_url":"https://twitter.com/Davincij15/status/1657185892514013186","author":"Davinci Jeremie","Retweets":37,"likes":296},{"text":"Why is bitcoin going down?","permanent_url":"https://twitter.com/AltcoinDailyio/status/1655672433716908033","author":"Altcoin Daily","Retweets":52,"likes":824},{"text":"Is Bitcoin unusable or too expensive for you? Try Bitcoin Cash. It always works and has tiny fees. On my new site Cashrain (still in beta) you can send thousands of BCH transactions simultaneously and instantly to your community. Learn about Bitcoin Cash: https://t.co/96kLYjArrd","permanent_url":"https://twitter.com/KimDotcom/status/1655576815006539776","author":"Kim Dotcom","Retweets":160,"likes":778},{"text":"Ethereum is so expensive!!\n\nHave they invented a cheaper chain?! 🤔","permanent_url":"https://twitter.com/AltcoinDailyio/status/1655296530495193088","author":"Altcoin Daily","Retweets":95,"likes":1277},{"text":"Dramatic increase in crypto investing in Europe. Dramatic decrease in crypto investing in the USA. \n\nWonder what the difference is? 🤔 https://t.co/RDBQvZmOai","permanent_url":"https://twitter.com/nlw/status/1655987684492312595","author":"Nathaniel Whittemore","Retweets":66,"likes":329},{"text":"YES! \n\nAnd guess who offers the most\n👏 useful\n👏 complete\n👏 transversal \nsolution for all businesses and worlds? 🛠️\n\nhttps://t.co/SXgbnvdcsF\n.\n.\
